In [1]:
import numpy as np

In [2]:
arr =(12,34,45,56,67,78,89,90)
print(arr)

(12, 34, 45, 56, 67, 78, 89, 90)


In [3]:
print(type(arr))

<class 'tuple'>


In [4]:
print("Hello namste")

Hello namste


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
print(np.__version__)

2.3.3


The python package Numpy,Which stands for "Numerical python".


Numpy is fundamental library for machine 



In [8]:
l1 =[1,2,3,4,5]
# print(l1)
l1

[1, 2, 3, 4, 5]

In [9]:
x = np.array(l1)
x

array([1, 2, 3, 4, 5])

find the diffrence between python list and numpy array

In [10]:
# create 1D array
x =np.array([23,43,54,32,65])
print(x)

[23 43 54 32 65]


In [11]:
x = np.random.rand(5)
x

array([0.15990447, 0.96254601, 0.4612736 , 0.3356424 , 0.04874038])

In [12]:
x = np.random.randint(5,16,10)
print(x)

[12 12 13 11  5 14 13  9  7  9]


In [13]:
# 2D array
y =np.array([[1,2,3],[4,5,6,],[7,8,9],[5,6,4]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 6 4]]


In [14]:
y =np.random.randint(5,16,(3,3))
print(y)

[[14  7  5]
 [ 7 11 10]
 [ 7  6  7]]


In [15]:
# 3D array
z =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
a =np.zeros((3,4), dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
a =np.ones((2,3,4), dtype=int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [18]:
a =np.full((5,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [19]:
a = 5 *np.eye(4,5, dtype=int)
print(a)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]


In [20]:
print("shape of array:", a.shape)


shape of array: (4, 5)


In [21]:
a.ndim

2

In [22]:
z.ndim

3

In [23]:
a.size

20

In [24]:
a.dtype

dtype('int64')

In [25]:
x.min()

np.int32(5)

In [26]:
x.max()

np.int32(14)

In [27]:
x.argmax()
print(x)

[12 12 13 11  5 14 13  9  7  9]


In [28]:
a.mean()
print(a)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]


Arithmetic Opreation

In [29]:
import numpy as np
a1 = np.array([1,2,3,4,5])
b1 = np.array([6,7,8,9,10])
a1 + b1



array([ 7,  9, 11, 13, 15])

In [30]:
a1 - b1

array([-5, -5, -5, -5, -5])

In [31]:
a1 * b1

array([ 6, 14, 24, 36, 50])

In [32]:
a1 / b1

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [33]:
a1 // b1

array([0, 0, 0, 0, 0])

In [34]:
a1 % b1

array([1, 2, 3, 4, 5])

In [35]:
a1 ** b1

array([      1,     128,    6561,  262144, 9765625])

Indexing is the process of accessing a single element from a sequence using its position or index.

It retrives a single element at a specific position.

Slicing refers to the process of extracting a portion of an array or a subarray. It allows you to

Access specific elements or ranges of elements in a Numpy array

In [36]:
print(x)

[12 12 13 11  5 14 13  9  7  9]


In [37]:
print(x[-5])

14


In [38]:
print(y)

[[14  7  5]
 [ 7 11 10]
 [ 7  6  7]]


In [39]:
print(y[0,2])

5


In [40]:
print(x[2:5])

[13 11  5]


In [41]:
print(x[:])

[12 12 13 11  5 14 13  9  7  9]


In [42]:
print(x[1:8:2])

[12 11 14  9]


In [43]:
np.flip(x)
print(x)


[12 12 13 11  5 14 13  9  7  9]


In [44]:
x[:] = 200
print(x)

[200 200 200 200 200 200 200 200 200 200]


In [45]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Broadcasting


In [46]:
l3 =[10,20,30,40,50]
arr =np.array(l3)
arr + 10

array([20, 30, 40, 50, 60])

In [47]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [49]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
slice =a[:5]
slice = slice * 10
slice


array([10, 20, 30, 40, 50])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Opration

In [52]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
B

array([[5, 6],
       [7, 8]])

In [55]:
np.dot( A,B )
# or
# A @ B

array([[19, 22],
       [43, 50]])

In [56]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation



Stacking Array ----> Means two array ko joad do (stack kar do)

In [57]:
#   vartical stacking ----->  usme hamesha vector ka use hota hai not uding matrix
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])


In [58]:
np.vstack((a,b))


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [59]:
# varical stack ko call karo or a and b ko tuple ke form  me bhej do

np.hstack((a,b)) # horizotnal means dono aaray ko joad dena



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
np.column_stack((a,b)) # hstack ye 1D array hai to uska muje 2D array karne ke liye colum_stack ka use kare

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

splitting Array


In [61]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
# split ko horizontal or vertical me split kar sakte hai
# muje horizotal ko split ke liye bich se cutout ho jayega and muje 2 array create ho jayega or do bhag me divide ho jayega 

np.hsplit(c,2) #ya np.hspli(c,4),(c,1) use kar sakte

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [63]:
# muje verical ko split ke liye bich se cutout ho jayega and muje 2 array create ho jayega or do bhag me divide ho jayega 

a =np.vsplit(c,4) #ya np.hspli(c,4),(c,1) use kar sakte

In [64]:
for i in a:
    print(i)

[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]
